### ISSUE TITLE
ModuleNotFoundError: No module named 'ops._private.harness'

### ISSUE THREAD

**Issue by mcfly722** [canonical/jhack#201] opened 2024-12-05 09:33 UTC
### Bug Description

Installation from snap not works out of the box.

Some additional steps for additional instalation components required?

### To Reproduce

```
sudo snap install --edge jhack
sudo snap connect jhack:dot-local-share-juju snapd
sudo snap connect jhack:ssh-read snapd
```
trying to use it:
```
jhack tail
```

```
WARNING:jhack./snap/jhack/439/lib/python3.12/site-packages/jhack/conf/conf.py:failed to create default user config in /root/.config/jhack/config.toml. You'll have to do that manually.
Traceback (most recent call last):
  File "/snap/jhack/439/bin/jhack", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/snap/jhack/439/lib/python3.12/site-packages/jhack/main.py", line 46, in main
    from jhack.scenario.snapshot import snapshot
  File "/snap/jhack/439/lib/python3.12/site-packages/jhack/scenario/snapshot.py", line 42, in <module>
    from jhack.scenario.integrations.darkroom import ops_port_to_scenario
  File "/snap/jhack/439/lib/python3.12/site-packages/jhack/scenario/integrations/darkroom.py", line 62, in <module>
    from ops._private.harness import _TestingModelBackend
ModuleNotFoundError: No module named 'ops._private.harness'
```

### Relevant log output

```shell
could not collect any logs, it fails on exception
```

**Comment by mcfly722** [comment] 2024-12-05 10:03
```
pip install ops
```
or
```
snap run --shell jhack
pip install ops
Requirement already satisfied: ops in /snap/jhack/439/lib/python3.12/site-packages (2.16.0)
Requirement already satisfied: PyYAML==6.* in /snap/jhack/439/lib/python3.12/site-packages (from ops) (6.0.2)
Requirement already satisfied: websocket-client==1.* in /snap/jhack/439/lib/python3.12/site-packages (from ops) (1.8.0)
```
does not helps too :(

**Comment by mcfly722** [comment] 2024-12-05 10:06
looks like problem with Edge version. Stable version works fine.
```
root@jjclient1:~# sudo snap install --stable jhack
jhack 0.4.4.0.2 from Pietro Pasotti (ppasotti) installed
root@jjclient1:~# sudo snap connect jhack:dot-local-share-juju snapd
root@jjclient1:~# sudo snap connect jhack:ssh-read snapd
root@jjclient1:~# jhack tail
WARNING:jhack./snap/jhack/411/lib/python3.8/site-packages/jhack/conf/conf.py:failed to create default user config in /root/.config/jhack/config.toml. You'll have to do that manually.
                                                                                             Jhack tail v0.4
                                                                     ┏━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
                                                                     ┃ timestamp ┃ data-integrator/3 ┃ postgresql/0  ┃ postgresql/1 ┃
                                                                     ┡━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━┩
                                                                     │ 10:06:11  │ update_status     │               │              │
                                                                     │ 10:06:09  │                   │ update_status │              │
                                                                     │ 10:05:54  │                   │               │ start        │
                                                                     └───────────┴───────────────────┴───────────────┴──────────────┘
```

**Comment by PietroPasotti** [comment] 2024-12-05 14:27
Thanks for the report. This was probably caused by a bad version pin in #200 
Should be fixed in the next edge release

**Closed by PietroPasotti** 2024-12-05 14:27 UTC
